### ISSUE TITLE
Neko crashes when selecting a date on AniList tracker 

### ISSUE THREAD

**Issue by nobile01** [CarlosEsco/Neko#1308]
### Steps to reproduce

1. Open a followed series
2. Select Tracking
3. Tap on Started/Finished reading date

### Expected behavior

After selecting either date option, it should pop up a date selection window. 

### Actual behavior

Neko crashes with this screen
![Screenshot_20230119-211849](https://user-images.githubusercontent.com/111714391/213611934-1252a18f-a059-4389-8877-d2ad2a55ee31.png)

### Crash logs

App version: 2.12.6 (standard, e2fcb49c6, 180, 2023-01-19T20:47:58.229748)
Android version: 13 (SDK 33)
Android build ID: TQ1A.221205.011
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.NoSuchFieldError: No static field $stable of type I in class Landroidx/compose/foundation/text/KeyboardActions; or its superclasses (declaration of 'androidx.compose.foundation.text.KeyboardActions' appears in base.apk)
at com.lanars.compose.datetextfield.DateInputViewKt.InputEditText(DateInputView.kt:19)
at com.lanars.compose.datetextfield.DateInputViewKt.SingleInputField(DateInputView.kt:237)
at com.lanars.compose.datetextfield.DateInputViewKt$DateInputField$3.invoke(DateInputView.kt:302)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
at androidx.compose.foundation.text.selection.SimpleLayoutKt$$ExternalSyntheticOutline0.m(R8$$SyntheticClass:5)
at com.lanars.compose.datetextfield.DateInputViewKt.CustomRow(DateInputView.kt:254)
at com.lanars.compose.datetextfield.DateInputViewKt.DateInputField(DateInputView.kt:17)
at com.lanars.compose.datetextfield.DateInputViewKt.DateTextField(DateInputView.kt:177)
at org.nekomanga.presentation.components.sheets.TrackingDateSheetKt$TrackingDateSheet$1.invoke(TrackingDateSheet.kt:1527)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
at org.nekomanga.presentation.components.sheets.BaseSheetKt$BaseSheet$1$1.invoke(BaseSheet.kt:233)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
at androidx.compose.material3.CardKt$Card$1.invoke(Card.kt:215)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:208)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:155)
at androidx.compose.material3.CardKt.Card(Card.kt:22)
at androidx.compose.material3.CardKt.ElevatedCard(Card.kt:12)
at org.nekomanga.presentation.components.sheets.BaseSheetKt$BaseSheet$1.invoke(BaseSheet.kt:95)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
at org.nekomanga.presentation.components.sheets.BaseSheetKt.BaseSheet-YlGCr2M(BaseSheet.kt:341)
at org.nekomanga.presentation.components.sheets.TrackingDateSheetKt.TrackingDateSheet(TrackingDateSheet.kt:255)
at org.nekomanga.presentation.screens.mangadetails.DetailsBottomSheetKt.DetailsBottomSheet(DetailsBottomSheet.kt:129)
at org.nekomanga.presentation.screens.MangaScreenKt$MangaScreen$6.invoke(MangaScreen.kt:298)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1$6.invoke(ModalBottomSheet.kt:215)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:223)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:425)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:494)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:22)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:302)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:58)
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:66)
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:48)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:127)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:36)
at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:18)
at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:76)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:362)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:827)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@cf94c5e, androidx.compose.ui.platform.MotionDurationScaleImpl@a1e583f, StandaloneCoroutine{Cancelling}@d88f50c, AndroidUiDispatcher@1422e55]

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************

### Neko version

App version: 2.12.6 (standard, e2fcb49c6, 180, 2023-01-19T20:47:58.229748) 

### Android version

Android version: 13 (SDK 33) Android build ID: TQ1A.221205.011 

### Device

Device brand: google Device manufacturer: Google Device name: raven Device model: Pixel 6 Pro Device product name: raven

### Other details

Changing tracking status, chapter number, and rating all work as expected; it's only crashing when selecting either date option. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.7
