### ISSUE TITLE
Neko Chrashes on Opening Manga, LayoutNode Compose error

### ISSUE THREAD

**Issue by master-bob** [CarlosEsco/Neko#1568]
### Steps to reproduce

1. Completely clean Neko install - cache cleared, data cleared
2. Open Neko
3. Go to Browse
4. Open a manga
5. If it doesn't crash, back out and open another one

### Expected behavior

Not crash 

### Actual behavior

Chrashes

### Crash logs

java.lang.Throwable: java.lang.IllegalStateException: LayoutNode should be attached to an owner
at androidx.compose.ui.node.LayoutNodeKt.requireOwner(Unknown Source:20)
at androidx.compose.ui.node.LayoutNode.getCollapsedSemantics$ui_release(Unknown Source:27)
at androidx.compose.ui.semantics.SemanticsNodeKt.SemanticsNode(Unknown Source:148)
at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SourceFile:1)
at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SourceFile:1)
at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SourceFile:1)
at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui_release(SourceFile:17)
at androidx.compose.ui.semantics.SemanticsNode.getChildren(SourceFile:3)
at androidx.compose.ui.semantics.SemanticsNode.getChildren(SourceFile:1)
at

(Also see next commentffor full)

### Neko version

2.13.5

### Android version

8

### Device

LG V20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by master-bob** [comment]
[2.13.5_LayoutChrash.txt](https://github.com/CarlosEsco/Neko/files/12869600/2.13.5_LayoutChrash.txt)

**Comment by CarlosEsco** [comment]
Do you still have this issue?

**Comment by master-bob** [comment]
I will see and let you know.

Thanks for getting back to me.

**Comment by master-bob** [comment]
This has not occurred on the latest release. I am closing this now.
