### ISSUE TITLE
app not installed

### ISSUE THREAD

**Issue by than10AM** [CarlosEsco/Neko#475]
When I try to install the app it gives me "app not installed". Is there a way to resolve this? I use LG K50S with android 9.

**Comment by arkon** [comment]
Use https://play.google.com/store/apps/details?id=com.aefyr.sai to get a more helpful error message.

**Comment by than10AM** [comment]
This is the error I got. 

java.io.IOException: Failed to allocate 20413109 because only 13918208 allocatable
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
	at android.os.Parcel.readParcelable(Parcel.java:2774)
	at android.os.Parcel.createException(Parcel.java:1945)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.openWrite(IPackageInstallerSession.java:256)
	at android.content.pm.PackageInstaller$Session.openWrite(PackageInstaller.java:836)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:94)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerSession.openWrite(PackageInstallerSession.java:605)
	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:82)
	at android.os.Binder.execTransact(Binder.java:756)

**Comment by CarlosEsco** [comment]
that looks like you are out of space on the phone

**Comment by than10AM** [comment]
Welp. Freeing up space fixed it. Thank you wizzard man🧙
