### ISSUE TITLE
Unable to open chapter with error "error returned from chapterResponse"

### ISSUE THREAD

**Issue by IktaS** [CarlosEsco/Neko#658]
### Device information
* Neko version: 2.5.6
* Android phone & version: Samsung Galaxy Note8 , Android version 9

## Steps to reproduce
Open [Asahina Wakaba to Marumaru na kareshi](https://mangadex.org/title/7cddbbff-fdf2-4630-b921-b7c3a17b9d9d/asahina-wakaba-to-marumaru-na-kareshi), chapter 15 in Neko.

### Expected behavior
Manga chapter is open normally

### Actual behavior
Loads, then back to chapter list, with error toast saying "error returned from chapterResponse"

### Other details
Snippet of log
```
1630245296012|E|||NEKO|	├ eu.kanade.tachiyomi.data.download.Downloader.downloadChapter$lambda-24$lambda-23(Downloader.kt:364)
	└ eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$XEu2kd0IJnd3IXMzmEVSZpL-vpA(Unknown Source:0)
java.lang.Exception: error returned from chapterResponse
1630245300344|E|||NEKO|	├ eu.kanade.tachiyomi.source.online.handlers.PageHandler$fetchPageList$2.invokeSuspend(PageHandler.kt:30)
	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
error returned from chapterResponse {"result":"error","errors":[{"id":"524eb5f9-8408-5783-b4fc-5b176572e923","status":404,"title":"not_found_http_exception","detail":"Chapter `6a4443e1-b548-4f02-8ae8-6d3b1e6744f7` not found.","context":null}]}
1630245300344|E|||NEKO|	├ eu.kanade.tachiyomi.source.online.handlers.PageHandler$fetchPageList$2.invokeSuspend(PageHandler.kt:81)
	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
error processing page list 
java.lang.Exception: error returned from chapterResponse
	at eu.kanade.tachiyomi.source.online.handlers.PageHandler$fetchPageList$2.invokeSuspend(PageHandler.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by IktaS** [comment]
This happened because a chapter is uploaded, user fetch chapter list, then the chapter is deleted in mangadex, then reuploaded again in mangadex. Causing a change in ID, thus the 404 and the illusion of the "same" chapter exist in Neko's chapter list. 

Fix: Refresh chapter list
