### ISSUE TITLE
Translation error 400

### ISSUE THREAD

**Issue by flolep2607** [CarlosEsco/Neko#853]
### Device information
* Neko version: 2.8.0.1
* Android phone & version: realme android 11

## Steps to reproduce
Chose French language for translation
### Expected behavior
Show french translation
### Actual behavior
Returning error 400
### Other details
Logs
`
App version: 2.8.0.1 (standard, 3172434, 140, 2022-01-27T21:32:16.561798)
Android version: 11 (SDK 30)
Android build ID: RMX2155_11_C.15
Device brand: realme
Device manufacturer: realme
Device name: RMX2155L1
Device model: RMX2155
Device product name: RMX2155EEA--------- beginning of system
02-12 10:57:52.310 19172 19172 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
02-12 10:58:12.939 19172 19414 E Parcel  : Reading a NULL string not supported here.
02-12 10:58:12.946 19172 19414 E Parcel  : Reading a NULL string not supported here.
02-12 10:58:12.983 19172 19414 E Parcel  : Reading a NULL string not supported here.
02-12 10:58:13.023 19172 19414 E Parcel  : Reading a NULL string not supported here.
02-12 10:58:13.027 19172 19414 E Parcel  : Reading a NULL string not supported here.
02-12 10:58:13.133 19172 19414 E Parcel  : Reading a NULL string not supported here.
02-12 10:58:19.847 19172 19414 E ||NEKO  : 	├ eu.kanade.tachiyomi.util.ApiResponseExtensionsKt.log(ApiResponseExtensions.kt:15)
02-12 10:58:19.847 19172 19414 E ||NEKO  : 	└ eu.kanade.tachiyomi.source.online.handlers.MangaHandler$fetchChapterList$2.invokeSuspend(MangaHandler.kt:13)
02-12 10:58:19.847 19172 19414 E ||NEKO  : error trying to view chapters {"result":"error","errors":[{"id":"9c346772-7b14-5982-b4b6-7b5888522762","status":400,"title":"validation_exception","detail":"Error validating \/translatedLanguage\/0: Does not match the regex pattern ^[a-zA-Z\\-]{2,5}$","context":null}]}
02-12 10:58:19.847 19172 19414 E ||NEKO  : 	├ eu.kanade.tachiyomi.util.ApiResponseExtensionsKt.log(ApiResponseExtensions.kt:18)
02-12 10:58:19.847 19172 19414 E ||NEKO  : 	└ eu.kanade.tachiyomi.source.online.handlers.MangaHandler$fetchChapterList$2.invokeSuspend(MangaHandler.kt:13)
02-12 10:58:19.847 19172 19414 E ||NEKO  : error response code 400
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	├ eu.kanade.tachiyomi.ui.manga.MangaDetailsPresenter$refreshAll$1$deferredChapters$1.invokeSuspend(MangaDetailsPresenter.kt:8)
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
02-12 10:58:19.848 19172 19414 E ||NEKO  : error with mangadex getting chapters
02-12 10:58:19.848 19172 19414 E ||NEKO  : java.lang.Exception: Error trying to view chapters http code: 400
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	at eu.kanade.tachiyomi.util.ApiResponseExtensionsKt.throws(ApiResponseExtensions.kt:12)
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.handlers.MangaHandler$fetchChapterList$2.invokeSuspend(MangaHandler.kt:14)
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-12 10:58:19.848 19172 19414 E ||NEKO  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
02-12 10:58:19.933 19172 19414 E ||NEKO  : 	├ eu.kanade.tachiyomi.util.ApiResponseExtensionsKt.log(ApiResponseExtensions.kt:15)
02-12 10:58:19.933 19172 19414 E ||NEKO  : 	└ eu.kanade.tachiyomi.source.online.handlers.ApiMangaParser$mangaDetailsParse$simpleChapters$1.invokeSuspend(ApiMangaParser.kt:11)
02-12 10:58:19.933 19172 19414 E ||NEKO  : error trying to aggregate for ed6ba867-0472-4f8f-af40-a2697fcd5cfc {"result":"error","errors":[{"id":"9c346772-7b14-5982-b4b6-7b5888522762","status":400,"title":"validation_exception","detail":"Error validating \/translatedLanguage\/0: Does not match the regex pattern ^[a-zA-Z\\-]{2,5}$","context":null}]}
02-12 10:58:19.933 19172 19414 E ||NEKO  : 	├ eu.kanade.tachiyomi.util.ApiResponseExtensionsKt.log(ApiResponseExtensions.kt:18)
02-12 10:58:19.933 19172 19414 E ||NEKO  : 	└ eu.kanade.tachiyomi.source.online.handlers.ApiMangaParser$mangaDetailsParse$simpleChapters$1.invokeSuspend(ApiMangaParser.kt:11)
02-12 10:58:19.933 19172 19414 E ||NEKO  : error response code 400`

**Comment by CarlosEsco** [comment]
Do you have just french enabled?  Or multiple languages?  What manga did you click into?

**Comment by flolep2607** [comment]
> Do you have just french enabled? Or multiple languages? What manga did you click into?

I just enabled french.
I get the error on every manga.

**Comment by flolep2607** [comment]
Ah the error is gone
